### ISSUE TITLE
Register version that works with most recent versions of EMX

### ISSUE THREAD

**Issue by hellemo** [EnergyModelsX/EnergyModelsRenewableProducers.jl#23]
EnergyModelsRenewableProducers is holding back updates of EMB, and this caused an incompatibility issue when using InvestmentModels as the package manager allowed upgrading EMI, but EMB was held back by EMRP.

Current workaround is to pin EMI to the previous version, but having a compatible version of EMPR would be preferable. 

Looks like this might be fixed by https://github.com/EnergyModelsX/EnergyModelsRenewableProducers.jl/pull/22

**Comment by JulStraus** [comment]
Yes. That will be fixed by #22 . Feel free to do a check for grammar issues or typos in the documentation. That is actually the only reason I added a reviewer there.
