### ISSUE TITLE
Abstract intermediate type for NonDisRES

### ISSUE THREAD

**Issue by Zetison** [EnergyModelsX/EnergyModelsRenewableProducers.jl#25]
Creating a new `NonDisRES`-like type (in combination with the EnergyModelsRenewableProducers package) which uses the `curtailment` variable creates some peculiar errors suggesting the key of such a node does not exist. 

A solution could be to introduce `abstract type AbstractNonDisRES <: EMB.Source end` and then define `NonDisRES` through `struct NonDisRES <: AbstractNonDisRES`. If we then use
```
function EMB.variables_node(m, 𝒩ⁿᵈʳ::Vector{AbstractNonDisRES}, 𝒯, modeltype::EnergyModel)
    @variable(m, curtailment[𝒩ⁿᵈʳ, 𝒯] ≥ 0)
end
```
other `NonDisRES`-like types that also needs such a variable can use `curtailment` as well (I guess the type `AbstractNonDisRES` can be used for the other constraints as well that dispatches on `NonDisRES`) . 

The workaround in the current setup is to define a new `curtailment` variable
```
function EMB.variables_node(m, 𝒩ⁿᵈʳ::Vector{PayAsProducedPPA}, 𝒯, modeltype::EnergyModel)
    @variable(m, curtailment_ppa[𝒩ⁿᵈʳ, 𝒯] ≥ 0)
end
```

**Comment by JulStraus** [comment]
Generally speaking, the workaround is entirely within the philosophy of EMB. In the current stage, it can remain that way. We plan to do soon a minor release based on the upcoming major release of `TimeStruct`. In this case, we can also introduce said `abstract type`.

**Comment by Zetison** [comment]
Just a general EMX remark about the issue: Even though the workaround works just fine, the struggle to figure out the issue was quite tedious (and the core issue was still unclear to me and @dqpinel after some hours of debugging). A strong suggestion for such core packages (as EnergyModelsRenewableProducers) to introduce intermediate abstract types (as suggested) I think would resolve the issue and allow for better extensibility of the packages in general.

**Comment by JulStraus** [comment]
Correction to myself: Somehow, it worked with a different index set to add a variable with an existing name. This should by all means not be possible in JuMP, as far as I know. Anyhow, the danger part into the documentation is well deserved.
